### ISSUE TITLE
R programming in the windows subsystem for linux

### ISSUE THREAD

**Issue by yshahhoseini** [jdblischak/blog.jdblischak.com#3]
Hello 
I have read your blog titled "R programming in the windows subsystem Linux". Followed your steps and installed rstudio and opened it via  http://localhost/rstudio/ . everything works fine. But I can't import data into rstudio-based WSL. I have copied the codes that I try and the errors that I get. I would appreciate it so much if you could please help me with my problem.
I have Windows 10 and installed Ubuntu 22.04.1 LST and R4.2 on my system.
when I type gtwd() code in R it gives me "/home/<username>/"

**code:**
version (1) 
ff <-read.csv("C:/Users/<username>/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc/LocalState/rootfs/home/yshahhosseini/df.csv")
version (2)
ff<- read.csv("/mnt/c/Users/<username>/AppData/Local/Packages/
              CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc/LocalState/rootfs/home/yshahhosseini/df.csv")
version(3)
ff <-read_xlsx("C:/Users/<username>/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc/LocalState/rootfs/home/yshahhosseini/DD.xlsx")
version(4)
ff <- read.csv("/home/<username>/df.csv")

**error in all of the codes is the same:**
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/yshahhosseini/dd.csv': No such file or directory

One more thing I was even able to copy and paste these file in the directory and can actually see them under "Files>-Home" in http://localhost/rstudio/, but still cant import them directly. I feel like I should do some settings in Ubuntu. But I am new to the system and cant think of anything.
Thank you in advance
Yasaman

**Comment by jdblischak** [comment]
Hi Yasaman. It looks like something strange is going on with your username. Does `getwd()` return `/home//` or `/home/yshahhosseini`?

I'm also confused why you are trying to access files in `AppData`. That is rather circular. When you are running R in the WSL, you should access Linux files via `/home/yshahhosseini` (or `~` for short to refer to your home directory), and you should access Windows files via `/mnt/c/Users/<put your Windows user name here (and make sure to delete the angle brackets)>`. In contrast, if you are running R on Windows, then you can access Linux files via `AppData`.

In general though, if you're going to start using the WSL regularly, I recommend moving your files to the WSL. Windows and Linux use different line endings, so you can run into issues mixing and matching. From the WSL terminal, you can copy files from Windows to WSL using a line like this (use `mv` to move instead of copy):

```sh
# copy file.txt on Windows Desktop to current working directory in Ubuntu
cp /mnt/c/Users/<Windows user name>/Desktop/file.txt .
```

I ran the following tests to confirm I can read/write to WSL and Windows from R running in the WSL. Could you please replace my usernames with yours, run the code, and then copy-paste the results to this thread?

```R
# my WSL username is jdblischak
getwd()
## [1] "/home/jdblischak"

# Test reading/writing to file on WSL
writeLines("test", con = "test.txt")
readLines("test.txt")
## [1] "test"
file.remove("test.txt")
## [1] TRUE

# Test reading/writing to file on Windows (username is john)
writeLines("test", con = "/mnt/c/Users/john/Desktop/test.txt")
readLines("/mnt/c/Users/john/Desktop/test.txt")
## "test"
file.remove("/mnt/c/Users/john/Desktop/test.txt")
## [1] TRUE
```

**Comment by yshahhoseini** [comment]
Hello 
Thank you for your prompt response and Pardon the delay in responding to you. I am Iranian and since last week was having a hard time digesting horrible news coming out of my country.

Regarding the matter, I just realized that when I write this code "sudo apachectl restart" on Ubuntu I receive this error"
httpd not running, trying to start
[Fri Sep 23 13:58:31.764604 2022] [core:warn] [pid 88] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Sep 23 13:58:31.764848 2022] [core:warn] [pid 88] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Sep 23 13:58:31.764858 2022] [core:warn] [pid 88] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

I would appreciate it if you could help me with solving this error.

**Comment by yshahhoseini** [comment]
I was able to solve the problem by installing opencpu and starting rstudio via this website https://www.opencpu.org/download.html

Now getting back to what my error was. The code getwd() returns "/home/yshahhosseini" in localhost/rstudio.

and the results of writing and running the code you mentioned in your last reply are as bellow 

> writeLines("test", con = "test.txt")
> readLines("test.txt")
[1] "test"
> file.remove("test.txt")
[1] TRUE
> writeLines("test", con = "/mnt/c/Users/yshahhosseini/test.txt")
> readLines("/mnt/c/Users/yshahhosseini/test.txt")
[1] "test"
> file.remove("/mnt/c/Users/yshahhosseini/Desktop/test.txt")
[1] FALSE
Warning message:
In file.remove("/mnt/c/Users/yshahhosseini/Desktop/test.txt") :
  cannot remove file '/mnt/c/Users/yshahhosseini/Desktop/test.txt', reason 'No such file or directory'

**Comment by jdblischak** [comment]
> Thank you for your prompt response and Pardon the delay in responding to you. I am Iranian and since last week was having a hard time digesting horrible news coming out of my country.

No need to apologize. The tragedy of Mahsa Amini's death is far more important than this technical discussion.

> [Fri Sep 23 13:58:31.764604 2022] [core:warn] [pid 88] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

You can safely ignore these error messages. I also receive them. They won't affect your ability to use R, RStudio Server, and OpenCPU.

> I was able to solve the problem by installing opencpu and starting rstudio via this website https://www.opencpu.org/download.html

I'm a little confused. The instructions from my blog post in the section [Install OpenCPU server](https://blog.jdblischak.com/posts/wsl-r/#install-opencpu-server) are based off the official OpenCPU instructions. Since you were already running RStudio Server, I assume you had already run these commands.

> and the results of writing and running the code you mentioned in your last reply are as bellow

Everything appears to be working. The only reason you got an error from `file.remove()` is because you included `Desktop/` in the path, whereas you ommitted this when running `writeLines()` and `readLines()`. You have to be consistent, so this will work:

```R
file.remove("/mnt/c/Users/yshahhosseini/test.txt")
```

**Comment by yshahhoseini** [comment]
I shed tears when I read your reply. Thank you for your support. 
I checked and now I can import data. I appreciate so much the time you took out of your schedule to help me with my problem. It seems like I was unfamiliar with the way of writing the path in the new rstudio-based WSL. 
With respect and regards

**Comment by jdblischak** [comment]
I'm glad everything is working now. Happy computing and best of luck to you during this difficult time.
